#+TITLE: An org mode template for submissions to the /International Journal of Osteoarchaeology/
#+AUTHOR: Frédéric Santos

This repository provides a minimal [[https://orgmode.org/][org mode]] template for writing scientific articles, with a convenient formatting for some Wiley journals. This template is more precisely formatted for the /[[https://onlinelibrary.wiley.com/journal/10991212][International Journal of Osteoarchaeology]]/, but should be suitable for any journal following [[https://onlinelibrary.wiley.com/page/journal/10991212/homepage/la_tex_class_files.htm][Wiley's APA-lato style]].

To use this template, simply download the folder ~ijoa-article/~ and work directly in this folder, by writing your main text in the file ~manuscript.org~. The output after a =C-c C-e l o= on the file =manuscript.org= should correspond to the file [[https://github.com/frederic-santos/org-template-ijoa/blob/master/ijoa-article/manuscrit.pdf][manuscript.pdf]].

** General Org settings
The following (minimal) configuration includes the mandatory settings to export your Org manuscript into a PDF.
In particular:
- Note that, starting with Org 9.5, Org mode now handles natively your bibliography, without the use of external packages such as [[https://github.com/jkitchin/org-ref][org-ref]].
- The APA-lato style makes use of the LaTeX class ~WileyNJD-v2~, provided by the publisher.

#+begin_src emacs-lisp :eval no
(use-package org
  :config
  (require 'org-tempo)
  (require 'ox-latex)
  ;; Settings for LaTeX/PDF export:
  (setq org-export-with-smart-quotes t) ;; de jolis guillemets français par défaut (avec babel !)
  (setq org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f"))
  ;; Add Wiley LaTeX class:
  (add-to-list 'org-latex-classes
	       '("WileyNJD-v2"
		 "\\documentclass{WileyNJD-v2}"
		 ("\\section{%s}" . "\\section*{%s}")
		 ("\\subsection{%s}" . "\\subsection*{%s}")
		 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")))
  ;; Org-babel settings:
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((latex . t)
     (org . t)
     (R . t)))
  (setq org-confirm-babel-evaluate nil)
  (setq org-src-preserve-indentation t)
  (setq org-edit-src-content-indentation 0)
  (add-hook 'org-babel-after-execute-hook 'org-display-inline-images) 
  (add-hook 'org-mode-hook 'org-display-inline-images))

;; Org-cite (for Org >= 9.5) :
(use-package oc
  :config
  (require 'oc-natbib)
  (setq org-cite-export-processors '((latex natbib)
                                     (t basic))))
#+end_src

** ~:ignore:~ tag
The =:ignore:= tag used for some org headlines is provided by the package [[https://code.orgmode.org/bzg/org-mode/raw/master/contrib/lisp/ox-extra.el][ox-extra]]. If you want to use it, you'll have to download this file in a folder that can be found by Emacs (i.e., a folder which is in its ~load-path~), and to add the following lines in your ~.emacs~:
#+begin_src emacs-lisp
(require 'ox-extra)
(ox-extras-activate '(ignore-headlines))
#+end_src

** Installing Lato fonts
Wiley's APA-lato style makes use of the Lato font.
- Installing Lato is straightforward for Windows users, since a Windows installer is included in the [[https://onlinelibrary.wiley.com/page/journal/10991212/homepage/la_tex_class_files.htm][archive provided by the publisher]].
- For Linux users, the makefile included in the archive does not seem to work properly (at least on my computer, with Linux Manjaro and TeXLive 2020). An install script (without any warranty: please check and adapt it if necessary!) is available [[https://tex.stackexchange.com/questions/558494/install-wileys-lato-fonts-onlinux?noredirect=1#comment1408514_558494][on Stackoverflow]].

** Useful resources
Writing a reproducible paper with org mode is incredibly convenient and pleasant; however, it may be challenging for beginners. If you are not /really/ familiar with org-mode, the following resources may be useful:
- [[http://archive.indianstatistics.org/tools/orgpapers.pdf][Using Emacs, Org-mode and R for Research Writing]], a great tutorial by Vikas Rawal
- [[http://cachestocaches.com/2018/6/org-literate-programming/][Literate programming with Org mode]], a blog post by Greg J. Stein
- [[https://orgmode.org/worg/org-contrib/babel/uses.html#sec-6][A (non exhasutive!) list of scientific papers prepared with org mode]]
